name: flutter_application_1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/199641361 1.png
    - assets/images/199641361 2.png
    - assets/images/Emmy 1.png
    - assets/images/Group 3.png
    - assets/images/hoian 1.png
    - assets/images/image 3.png
    - assets/images/journey1.png
    - assets/images/journey2.png
    - assets/images/Location Pin 2 1.png
    - assets/images/Tuan Tran 1.png
    - assets/images/Vector.png
    - assets/images/Vector 1.png
    - assets/images/Vector 6.png
    - assets/images/Group 7.png
    - assets/images/Group 8.png
    - assets/images/Group 9.png
    - assets/images/Explore-Active.png
    - assets/images/Notifications-Inactive.png
    - assets/images/Profile-Inactive.png
    - assets/images/Trips-Inactive.png
    - assets/images/Chat-Inactive.png
    - assets/images/Da Nang - Ba Na - Hoi An.png
    - assets/images/Hanoi - Ha Long Bay.png
    - assets/images/Melbourne - Sydney.png
    - assets/images/Mask Group.png
    - assets/images/New Destination in Danang City.png
    - assets/images/1 Flight Ticket.png
    - assets/images/Visit Korea in this Tet Holiday.png
    - assets/images/Profile-Inactive.png
    - assets/images/Trips-Inactive.png
    - assets/images/Trips-Active.png
    - assets/images/Explore-Inactive.png
    - assets/images/Vector 5.png
    - assets/images/hat.png
    - assets/images/Vector 4.png
    - assets/images/Vector 2.png
    - assets/images/Vector 7.png
    - assets/images/Group 1.png
    - assets/images/Lanho.png
    - assets/images/Logo.png
    - assets/images/Group 51.png
    - assets/images/Group 50.png
    - assets/images/HoanKiemLake.png
    - assets/images/Chat-Active.png
    - assets/images/Explore-Active.png
    - assets/images/Notifications-Active.png
    - assets/images/Profile-Active.png
    - assets/images/Group 69.png
    - assets/images/DaNang DownTown !!!! Hello VietNam.png


  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets\fonts\SF-Pro-Display-Black.otf
        - asset: assets\fonts\SF-Pro-Display-BlackItalic.otf
        - asset: assets\fonts\SF-Pro-Display-Bold.otf
        - asset: assets\fonts\SF-Pro-Display-BoldItalic.otf
        - asset: assets\fonts\SF-Pro-Display-Heavy.otf
        - asset: assets\fonts\SF-Pro-Display-HeavyItalic.otf
        - asset: assets\fonts\SF-Pro-Display-Light.otf
        - asset: assets\fonts\SF-Pro-Display-LightItalic.otf
        - asset: assets\fonts\SF-Pro-Display-Medium.otf
        - asset: assets\fonts\SF-Pro-Display-MediumItalic.otf
        - asset: assets\fonts\SF-Pro-Display-Regular.otf
        - asset: assets\fonts\SF-Pro-Display-RegularItalic.otf
        - asset: assets\fonts\SF-Pro-Display-Semibold.otf
        - asset: assets\fonts\SF-Pro-Display-SemiboldItalic.otf
        - asset: assets\fonts\SF-Pro-Display-Thin.otf
        - asset: assets\fonts\SF-Pro-Display-ThinItalic.otf
        - asset: assets\fonts\SF-Pro-Display-Ultralight.otf
        - asset: assets\fonts\SF-Pro-Display-UltralightItalic.otf
          weight: 700
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
